### ISSUE TITLE
The VPC  Has Dependencies and Cannot be Deleted

### ISSUE THREAD

**Issue by Tensho** [terraform-aws-modules/terraform-aws-vpc#283] opened 2019-06-11 15:05 UTC
I have quite a straightforward module usage:
```
# main.tf

module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "1.59.0"

  name = "${var.name}"
  cidr = "${var.cidr}"
  azs  = "${var.azs}"

  enable_dns_hostnames = true

  enable_nat_gateway     = true
  single_nat_gateway     = false
  one_nat_gateway_per_az = true

  public_subnets   = "${var.public_subnets}"
  private_subnets  = "${var.private_subnets}"
  database_subnets = "${var.db_subnets}"

  nat_eip_tags = "${var.nat_eip_tags}"

  tags = {
    Terraform  = "true"
    Terragrunt = "true"
  }
}
```
A strange thing happens when I try to **apply** changes for re-creating new VPC within the module. I've changed VPC CIDR block and expect everything should be deleted and re-created from scratch. However, I get the next error:
```
-/+ module.vpc.aws_vpc.this (new resource required)
      id:                               "vpc-0626034ed6648e300" => <computed> (forces new resource)
      ...
      cidr_block:                       "10.200.0.0/16" => "10.12.0.0/16" (forces new resource)
      ...

module.vpc.aws_vpc.this: Destroying... (ID: vpc-0626034ed6648e300)
module.vpc.aws_vpc.this: Still destroying... (ID: vpc-0626034ed6648e300, 10s elapsed)
module.vpc.aws_vpc.this: Still destroying... (ID: vpc-0626034ed6648e300, 20s elapsed)
...
aws_vpc.this: DependencyViolation: The vpc 'vpc-0626034ed6648e300' has dependencies and cannot be deleted.
	status code: 400, request id: 40cfa5b7-4a3f-418c-9f2f-8fa450dda882
```
Nevertheless, if I **destroy** resources before **apply** everything is fine:
```
...
  - module.vpc.aws_db_subnet_group.database

  - module.vpc.aws_eip.nat[0]

  - module.vpc.aws_eip.nat[1]

  - module.vpc.aws_internet_gateway.this

  - module.vpc.aws_route.private_nat_gateway[0]

  - module.vpc.aws_route.private_nat_gateway[1]

  - module.vpc.aws_route_table.private[0]

  - module.vpc.aws_route_table.private[1]

  - module.vpc.aws_vpc.this
...
module.vpc.aws_vpc.this: Destroying... (ID: vpc-0626034ed6648e300)
module.vpc.aws_vpc.this: Destruction complete after 1s

Destroy complete! Resources: 9 destroyed.
```
Seems like there is a problem with the dependency graph resolution, but I don't see anything abnormal in the plan. Does anyone have the same issue?

**Comment by antonbabenko** [comment] 2019-06-13 17:25
I think I found the problem (using 0.12, but should be similar). Internet gateway or NAT gateway should be deleted together with the old VPC, but instead, it is not deleting them but it tries to change VPC id from old to new. Therefore old VPC can't be deleted.

```
  ~ module.vpc.aws_internet_gateway.this
      vpc_id:                           "vpc-084a3314b22f1ffe0" => "${local.vpc_id}"
```

I could not reproduce the issue with few resources.

Since you can delete VPC and retry again, I will close this issue. I don't have time to work on this myself.

**Closed by antonbabenko** 2019-06-13 17:25 UTC

**Comment by demisx** [comment] 2019-07-31 19:30
I have the same issue in v0.12. Terraform is not able to delete the VPC, but I have no problem deleting it from AWS Console UI.

```
Terraform v0.12.5
+ provider.aws v2.17.0
```

**Comment by nickkadams** [comment] 2019-08-11 16:09
Same issue for me: Error: Error deleting VPC: DependencyViolation: The vpc 'vpc-*' has dependencies and cannot be deleted. status code: 400

```
Terraform v0.12.6
+ provider.aws v2.23.0
```

**Comment by JuanAnsio** [comment] 2019-09-04 15:59
Same here. It worked after I manually deleted some security groups attached to the VPC. Those SG were referencing another SG from the VPC, so probably Terraform gets stuck because is trying to delete first the referenced ones and AWS doesn't allow it

`
Terraform v0.12.6
+ provider.aws v2.24
`

**Comment by marcofranssen** [comment] 2019-10-24 12:08
We are resolving that using the following approach:

```terraform
resource "null_resource" "clean-k8s-resources" {
  provisioner "local-exec" {
    when    = "destroy"
    command = "./bin/clean-k8s-resources.sh ${var.region} ${local.cluster_name} ${module.vpc.vpc_id}"
  }
}
```

We use a script to get the resources using a python script to cleanup those first so the destroy does not get stuck.

I think there might be a way to extend this module to resolve this issue from within this module.

**Comment by githubleime** [comment] 2020-02-13 21:42
> I have the same issue in v0.12. Terraform is not able to delete the VPC, but I have no problem deleting it from AWS Console UI.
> 
> ```
> Terraform v0.12.5
> + provider.aws v2.17.0
> ```

I just faced the same issue, I found when deleting VPC from UI, it actually first delete security groups first. Thant's why deleting from UI works, but not from aws CLI, boto3 or terraform.

**Comment by agconti** [comment] 2020-03-16 20:13
@marcofranssen what's inside of your `clean-k8s-resources.sh`?

**Comment by nagulvali** [comment] 2020-07-07 11:40
Error: Error deleting VPC: DependencyViolation: The vpc 'vpc-063c05090f88bda63' has dependencies and cannot be deleted.
        status code: 400, request id: cf4dc9b7-0de6-4533-80b5-de9ea6723d26

Able to delete from UI console without any dependency issues.

**Comment by Emc1992** [comment] 2020-10-11 16:20
Just got this in terraform v13.4 with aws v3.10.0 - was able to delete via aws console

**Comment by adriaanbd** [comment] 2020-10-17 05:57
> 
> 
> Just got this in terraform v13.4 with aws v3.10.0 - was able to delete via aws console

Same issue in here with the above!

**Comment by onitake** [comment] 2020-11-25 18:39
I think this issue should be reopened.
Requiring manual deletion of resources when changing the VPC range is not very user friendly.

**Comment by onitake** [comment] 2020-11-26 10:34
The workaround mentioned by @antonbabenko (delete all internet and NAT gateways) did help, but this is not a very practicable approach when using CI/CD. 

As long as the gateways are created by the same Terraform script, the AWS provider should detect the dependency and try to re-deploy it when VPC parameters are changed.

**Comment by antonbabenko** [comment] 2020-11-26 10:38
@onitake I completely agree that all dependencies created by the module should be respected and destroyed automatically.

If anyone can figure out HOW to solve this and send a PR, I will be extremely glad to review it and merge. I don't have time to work on this and an understanding of how to reproduce the issue myself.

**Comment by mmbcn** [comment] 2020-11-30 11:15
Having same issue here.  Using Terraform v.0.13.5 aws provider 3.18.0 and only thing that is sttached tot he VPC is 3 SG. I can delete it from console or over cli without any issues. Terraform fails to delete it cause of dependencies even when trying multiple times. 


```
<Response><Errors><Error><Code>DependencyViolation</Code><Message>The vpc 'vpc-0f528a336d9bb8bea' has dependencies and cannot be deleted.</Message></Error></Errors><RequestID>7568ff6c-c411-45e0-98e0-fa6896140e11</RequestID></Response>
2020-11-30T12:09:29.826+0100 [DEBUG] plugin.terraform-provider-aws_v3.18.0_x5: 2020/11/30 12:09:29 [DEBUG] [aws-sdk-go] DEBUG: Validate Response ec2/DeleteVpc failed, attempt 0/25, error DependencyViolation: The vpc 'vpc-0f528a336d9bb8bea' has dependencies and cannot be deleted.
2020-11-30T12:09:29.826+0100 [DEBUG] plugin.terraform-provider-aws_v3.18.0_x5: 	status code: 400, request id: 7568ff6c-c411-45e0-98e0-fa6896140e11
2020-11-30T12:09:29.826+0100 [DEBUG] plugin.terraform-provider-aws_v3.18.0_x5: 2020/11/30 12:09:29 [TRACE] Waiting 10s before next try 
```


Does anyone have a solution/workaround until it is fixed?

**Comment by phil-smarsh** [comment] 2020-12-23 19:53
Experienced the same with Terraform 0.13.5 and AWS provider 2.55.
Manually deleting VPC and NAT gateway fixed it but as others have stated, not really a good/clean solution for CICD.

**Comment by jogindercc** [comment] 2021-02-07 12:18
We Experienced the same issue, It was due to TransitGW created outside of terraform. 
Once we deleted the TransitGW.  VPC was deleted within 5sec.

**Comment by emctl** [comment] 2021-02-08 00:30
Is it over simplifying to say that we could get TF to tag with a UUID and "delete all TF created resources + resources containing UUID" or the fact that if we are deleting that we delete all resource that have exist within a given vpc?

**Comment by lkysow** [comment] 2021-03-22 19:04
We're seeing this too just recently.

```hcl
provider "aws" {
  version = ">= 2.28.1"
}

module "vpc" {
  count   = var.cluster_count
  source  = "terraform-aws-modules/vpc/aws"
  version = "2.77.0"

  name                 = "blah"
  cidr                 = "10.0.0.0/16"
  azs                  = data.aws_availability_zones.available.names
  private_subnets      = ["10.0.1.0/24", "10.0.2.0/24", "10.0.3.0/24"]
  public_subnets       = ["10.0.4.0/24", "10.0.5.0/24", "10.0.6.0/24"]
  enable_nat_gateway   = true
  single_nat_gateway   = true
  enable_dns_hostnames = true

  public_subnet_tags = {
    "kubernetes.io/cluster/consul-k8s-${random_id.suffix[count.index].dec}" = "shared"
    "kubernetes.io/role/elb"                                                = "1"
  }

  private_subnet_tags = {
    "kubernetes.io/cluster/consul-k8s-${random_id.suffix[count.index].dec}" = "shared"
    "kubernetes.io/role/internal-elb"                                       = "1"
  }

  tags = var.tags
}

```

**Comment by mohnishbasha** [comment] 2021-09-08 00:05
i am also facing a similar issue, it looks like a lifecycle issue on destroy:

module.vpc.module.vpc.aws_vpc.this[0]: Still destroying... [id=vpc-xxxx, 4m50s elapsed]

│ Error: Error deleting VPC: DependencyViolation: The vpc 'vpc-xxxxx' has dependencies and cannot be deleted.
│   status code: 400, request id: cf6a97b1-b621-468d-8c47-70d33b51c2e1

**Comment by timblaktu** [comment] 2022-09-16 20:56
Seeking clarity on status here[^1]... this issue has been closed but there is no resolution in this repo, the "official" aws vpc module. I see what looks like the solution, described twice in the context of _how-to-workaround-this-bug-for-users-of-this-module_ (listed below). I understand that certain features can't be just removed wily-nily due to existing users, but ***if this is such an insidious problem for users of this module, shouldn't it at least be documented that best practice is to not let this module manage its default security group with instructions and examples of the workaround?*** That would have seemed to be an appropriate action at the closing of this Issue.

1. Suggestions to create the VPC's default security group outside the module and pass it ***somehow***. [@mohnishbasha provided an eks-specific solution for this](https://github.com/terraform-aws-modules/terraform-aws-vpc/issues/283#issuecomment-914758128), passing the VPC SG into the eks module, but I'm not sure this applies to all cases.
    1. I'm also inferring that [`input_manage_default_security_group`](https://github.com/terraform-aws-modules/terraform-aws-vpc#input_manage_default_security_group) should be set to `false`?

2. @juandiegopalomino 's fix over in opta](https://github.com/run-x/opta/pull/407/files), in which he did essentially the same thing in his (eks module) use case:
    1. separately created the security_group
    2. pass 1. to the eks module `security_group_ids` input
    3. apply `ignore_changes` lc policy to 2, i.e. `eks.vpc_config[0].security_group_ids`, so that this security group won't  be "managed" by the containing resource, the eks cluster.
    4. [Some other stuff I don't understand](https://github.com/run-x/opta/pull/407/files#diff-cb6d14067beed077847b66cd05e2227d69cde25747163062cdf426ef00781e06R154)

Let me know if I'm missing anything. I'm basically going to propose the same patch in the eks blueprints corresponding issue.

[^1]: because I'm hitting this too, of course. See my [report of this bug over in the eks blueprints repo](https://github.com/aws-ia/terraform-aws-eks-blueprints/issues/968).

**Comment by bryantbiggs** [comment] 2022-09-17 11:29
all of the issues here seem to refer to EKS which points to a well known issue with the VPC CNI https://github.com/aws/amazon-vpc-cni-k8s/issues/1447
