### ISSUE TITLE
Subnets

### ISSUE THREAD

**Issue by ayotec2015** [terraform-aws-modules/terraform-aws-vpc#251] opened 2019-05-06 10:44 UTC
HI, 

I am pretty new to this. I am using your module but it seems each time I run terraform the IP changes forcing VPC to rebuild because subnets changes and then forces EKS to rebuild is there a way to stop the IP changing in the subnets ? 

Sorry if am asking a very obvious question. I am just pretty new to this.

Thanks

**Comment by ayotec2015** [comment] 2019-05-06 12:08
https://github.com/terraform-aws-modules/terraform-aws-vpc/issues/114 . same issue but am using /24

name = "puppy-vpc"
  cidr = "10.0.0.0/16"


  azs             = ["eu-west-2a", "eu-west-2b", "eu-west-2c"]
  public_subnets  = ["10.0.2.0/24", "10.0.3.0/24", "10.0.4.0/24"]
  private_subnets = ["10.0.65.0/19", "10.0.97.0/19", "10.0.129.0/19"]

**Comment by dpiddockcmp** [comment] 2019-05-06 13:05
Hi,

The problem is not the /24 public subnets but your /19 private subnets.

AWS calculates the "correct" network address based on the input CIDR values, which may differ from the values set in Terraform. You need to update your `private_subnets` to also use these correct values: `"10.0.64.0/19", "10.0.96.0/19", "10.0.128.0/19"`

Maybe file a bug against the AWS provider so that the vpc and subnet resources also do this translation.

**Comment by ayotec2015** [comment] 2019-05-06 21:18
Hey 

I have spent 2 days trying to resolve this problem. Thanks so much you have made my day :)  Just 1 quick question. How do you know what subnet ranges I can use ? I have 2 more environments with same problem.

**Comment by dpiddockcmp** [comment] 2019-05-07 11:27
Easiest way is to use an ip calculator. There are plenty of options out there. An example is http://jodies.de/ipcalc . Put in an address in your range and the CIDR value, hit calculate and take the `Network` result.

**Comment by ayotec2015** [comment] 2019-05-07 16:18
Thanks for your help on that. Really helpful.  
I have another question. I am not able to connect to the Nodes. I am guessing its the VPC ACL that isn't letting connection to the nodes. What would be the best way to allow access to the nodes

**Comment by dpiddockcmp** [comment] 2019-05-10 13:07
You mentioned EKS so I guess you're talking about kubernetes nodes?

Depends on how you want to access nodes. Do you mean command line access?

If you want to use SSH then you will have to create a key pair resource and pass it to the node launch template/configuration.
Remember that by default AWS security groups do not allow ingress from anywhere. 
Do the nodes have public IPs? If so, you need to edit the security group and allow access from your IP.
If not, you need to create a bastion server in the public subnet, allow SSH access from your IP and grant it SSH access to the nodes.

Alternatively, you can use AWS Systems Manager Session Manager to gain access without SSH or ingress security rules. You will need to install an agent in the nodes (e.g. via user data or creating an AMI), add the necessary IAM permissions and then use the AWS console. 
https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager.html

**Comment by ayotec2015** [comment] 2019-05-21 11:41
HI 

I have managed to get ssh key working, I have also opened the port 22, I also enabled Public IP and public DNS for nodes. I am still not able to connect to the nodes. I am not sure if there is something in the VPC blocking me from connecting to the nodes directly.

**Comment by antonbabenko** [comment] 2019-06-13 20:43
Closing this issue, as it is not related to the module.

**Closed by antonbabenko** 2019-06-13 20:43 UTC
