### ISSUE TITLE
Call to function "element" failed: cannot use element function with an empty list

### ISSUE THREAD

**Issue by zakswindow** [terraform-aws-modules/terraform-aws-vpc#400] opened 2020-03-02 16:06 UTC
Hi,
I am trying to destroy everything that i created with terraform but i am getting a new error. 

```
**`Error: Error in function call

  on ../modules/vpc/main.tf line 935, in resource "aws_route_table_association" "private":
 935:   route_table_id = element(
 936:
 937:
 938:
    |----------------
    | aws_route_table.private is empty tuple
    | count.index is 3
    | var.single_nat_gateway is false

Call to function "element" failed: cannot use element function with an empty
list.


Error: Error in function call

  on ../modules/vpc/main.tf line 946, in resource "aws_route_table_association" "database":
 946:     coalescelist(aws_route_table.database.*.id, aws_route_table.private.*.id),
    |----------------
    | aws_route_table.database is empty tuple
    | aws_route_table.private is empty tuple

Call to function "coalescelist" failed: no non-null arguments.


Error: Error in function call

  on ../modules/vpc/main.tf line 946, in resource "aws_route_table_association" "database":
 946:     coalescelist(aws_route_table.database.*.id, aws_route_table.private.*.id),
    |----------------
    | aws_route_table.database is empty tuple
    | aws_route_table.private is empty tuple

Call to function "coalescelist" failed: no non-null arguments.`**
```

Any idea why this is happening?

**Comment by ivanmb** [comment] 2020-03-04 20:03
+1 I have this same error when trying to change an existing VPC to have multiple NAT Gateways for each AZ.

Before
```
single_nat_gateway = true
one_nat_gateway_per_az = false
```

after 

```
single_nat_gateway = false
one_nat_gateway_per_az = true
```

When running `terraform plan` I get a similar error due to `aws_subnet.public is empty tuple`

**Comment by samuel-elliott** [comment] 2020-03-29 19:28
Getting this as well with Terraform 0.12.24 and provider.aws 2.55 working on creating two AZs in one region, one public subnet per AZ and each with their own NAT gateway. I deleted my network stack to try and resolve it not properly updating the sg-XXXXX identifier from a terraform_remote_state data source, thus erroring out, and have ran into this:

```
Error: Error in function call

  on network-subnets.tf line 69, in resource "aws_nat_gateway" "gw":
  69:   subnet_id     = element(aws_subnet.public[*].id, count.index)
    |----------------
    | aws_subnet.public is empty tuple
    | count.index is 0

Call to function "element" failed: cannot use element function with an empty
list.


Error: Error in function call

  on network-subnets.tf line 69, in resource "aws_nat_gateway" "gw":
  69:   subnet_id     = element(aws_subnet.public[*].id, count.index)
    |----------------
    | aws_subnet.public is empty tuple
    | count.index is 1
```

Call to function "element" failed: cannot use element function with an empty
list.


The following was working just fine half an hour ago, creating two subnets and two NAT gateways:

_network-subnets.tf_

```
# Create var.az_count public subnets, each in a different AZ
resource "aws_subnet" "public" {
  count                   = var.az_count
  cidr_block              = cidrsubnet(aws_vpc.Rearc.cidr_block, 8, count.index)
  availability_zone       = data.aws_availability_zones.available.names[count.index]
  vpc_id                  = aws_vpc.Rearc.id
  map_public_ip_on_launch = true

  tags = {
    name = "Public Subnet"
    Region = var.aws_region
    Environment = var.environment
  }
}
```

*snip*


```
# Create a NAT gateway with an Elastic IP for each private subnet to get internet connectivity
resource "aws_eip" "gw" {
  count      = var.az_count
  vpc        = true
  depends_on = [aws_internet_gateway.gw]

  tags = {
    Name = "Elastic IP Address"
    Region =var.aws_region
    Environment = var.environment
  }
}

resource "aws_nat_gateway" "gw" {
  count         = var.az_count
  subnet_id     = element(aws_subnet.public[*].id, count.index)
  allocation_id = element(aws_eip.gw[*].id, count.index)

  tags = {
    Name = "NAT Gateway"
    Region = var.aws_region
    Environment = var.environment
  }
}
```


The only way I was able to resolve this was to delete the terraform.tfstate file in the pertinent subdirectory in its S3 bucket, the accompanying MD5 sum entry in its DynamoDB table, and rebuild from scratch.

I've made a backup of the current network directory if further information is requested.

**Comment by joy-george** [comment] 2020-04-10 13:27
I guess this will occur in cases where we are trying to create public subnets < number of azs

**Comment by xueshanf** [comment] 2020-06-04 02:59
> I guess this will occur in cases where we are trying to create public subnets < number of azs

Nice thought, but I hard-coded 3  AZ's name (I have 3 subnets) and it still gives the error.

**Comment by xueshanf** [comment] 2020-06-04 05:06
> > I guess this will occur in cases where we are trying to create public subnets < number of azs
> 
> Nice thought, but I hard-coded 3 AZ's name (I have 3 subnets) and it still gives the error.

Actually my  hard-coded test probably isn't right.  My original  code is `azs             = data.aws_availability_zones.available.names` which has count 4 in us-west-2, but I defined only 3 subnets,  hence the error. I will stick with NAT per subnets configuration.

**Comment by daveVPM** [comment] 2020-07-08 12:50
Also getting the same error when standing up a new VPC, with static assignment of 3 AZs and 3 public subnets (one per AZ).  Ideally would like to see 1 NGW per AZ, using the following flags:

- single_nat_gateway = false
- one_nat_gateway_per_az = true
- enable_nat_gateway = true

Getting the following error (Terraform v0.12.26 and AWS ">= 2.28.1"):
`Error: Error in function call

  on .terraform/modules/vpc/terraform-aws-vpc-2.6.0/main.tf line 795, in resource "aws_nat_gateway" "this":
 795:   subnet_id = element(
 796: 
 797: 
 798: 
    |----------------
    | aws_subnet.public is empty tuple
    | count.index is 2
    | var.single_nat_gateway is false

Call to function "element" failed: cannot use element function with an empty
list.
`

**Comment by abhishekkanojiaperion** [comment] 2020-08-06 19:44
I'm getting same error using terragrunt. 
``` 
inputs = {
  name = "vpc"
  cidr = "10.230.0.0/16"
  azs             = ["us-west-2a", "us-west-2b", "us-west-2c"]
  private_subnets = ["10.230.0.0/20", "10.230.16.0/20", "10.230.32.0/20"]
  public_subnets  = ["10.230.48.0/20", "10.230.64.0/20", "10.230.80.0/20"]
  #single_nat_gateway = true
  enable_nat_gateway   = true
  enable_vpn_gateway   = true #Virtual Private Gateway id=vgw-xxxxxxxxx
  enable_s3_endpoint   = true
  enable_dns_hostnames = true
 ```
terragrunt version v0.21.11
Terraform v0.12.20
provider.aws: version = "~> 3.0"


```
Error: Error in function call
00:51:50  
00:51:50    on .terraform/modules/local_vpc/terraform-aws-vpc-2.21.0/main.tf line 905, in resource "aws_route" "private_nat_gateway":
00:51:50   905:   route_table_id         = element(aws_route_table.private.*.id, count.index)
00:51:50      |----------------
00:51:50      | aws_route_table.private is empty tuple
00:51:50      | count.index is 1
00:51:50  
00:51:50  Call to function "element" failed: cannot use element function with an empty
00:51:50  list.
00:51:50  
00:51:50  
00:51:50  Error: Error in function call
00:51:50  
00:51:50    on .terraform/modules/local_vpc/terraform-aws-vpc-2.21.0/main.tf line 905, in resource "aws_route" "private_nat_gateway":
00:51:50   905:   route_table_id         = element(aws_route_table.private.*.id, count.index)
00:51:50      |----------------
00:51:50      | aws_route_table.private is empty tuple
00:51:50      | count.index is 2
00:51:50  
00:51:50  Call to function "element" failed: cannot use element function with an empty
00:51:50  list.
00:51:50  
00:51:50  
00:51:50  Error: Error in function call
00:51:50  
00:51:50    on .terraform/modules/local_vpc/terraform-aws-vpc-2.21.0/main.tf line 905, in resource "aws_route" "private_nat_gateway":
00:51:50   905:   route_table_id         = element(aws_route_table.private.*.id, count.index)
00:51:50      |----------------
00:51:50      | aws_route_table.private is empty tuple
00:51:50      | count.index is 0
00:51:50  
00:51:50  Call to function "element" failed: cannot use element function with an empty
00:51:50  list.
00:51:50  
00:51:50  
00:51:50  Error: Error in function call
00:51:50  
00:51:50    on .terraform/modules/local_vpc/terraform-aws-vpc-2.21.0/main.tf line 929, in resource "aws_route_table_association" "private":
00:51:50   929:   route_table_id = element(
00:51:50   930: 
00:51:50   931: 
00:51:50   932: 
00:51:50      |----------------
00:51:50      | aws_route_table.private is empty tuple
00:51:50      | count.index is 2
00:51:50      | var.single_nat_gateway is false
00:51:50  
00:51:50  Call to function "element" failed: cannot use element function with an empty
00:51:50  list.
00:51:50  
00:51:50  
00:51:50  Error: Error in function call
00:51:50  
00:51:50    on .terraform/modules/local_vpc/terraform-aws-vpc-2.21.0/main.tf line 929, in resource "aws_route_table_association" "private":
00:51:50   929:   route_table_id = element(
00:51:50   930: 
00:51:50   931: 
00:51:50   932: 
00:51:50      |----------------
00:51:50      | aws_route_table.private is empty tuple
00:51:50      | count.index is 1
00:51:50      | var.single_nat_gateway is false
00:51:50  
00:51:50  Call to function "element" failed: cannot use element function with an empty
00:51:50  list.
00:51:50  
00:51:50  
00:51:50  Error: Error in function call
00:51:50  
00:51:50    on .terraform/modules/local_vpc/terraform-aws-vpc-2.21.0/main.tf line 929, in resource "aws_route_table_association" "private":
00:51:50   929:   route_table_id = element(
00:51:50   930: 
00:51:50   931: 
00:51:50   932: 
00:51:50      |----------------
00:51:50      | aws_route_table.private is empty tuple
00:51:50      | count.index is 0
00:51:50      | var.single_nat_gateway is false
00:51:50  
00:51:50  Call to function "element" failed: cannot use element function with an empty
00:51:50  list.
00:51:50  
00:51:50  
00:51:50  Error: Invalid index
00:51:50  
00:51:50    on .terraform/modules/local_vpc/terraform-aws-vpc-2.21.0/main.tf line 989, in resource "aws_route_table_association" "public":
00:51:50   989:   route_table_id = aws_route_table.public[0].id
00:51:50      |----------------
00:51:50      | aws_route_table.public is empty tuple
00:51:50  
00:51:50  The given key does not identify an element in this collection value.
00:51:50  
00:51:50  
00:51:50  Error: Invalid index
00:51:50  
00:51:50    on .terraform/modules/local_vpc/terraform-aws-vpc-2.21.0/main.tf line 989, in resource "aws_route_table_association" "public":
00:51:50   989:   route_table_id = aws_route_table.public[0].id
00:51:50      |----------------
00:51:50      | aws_route_table.public is empty tuple
00:51:50  
00:51:50  The given key does not identify an element in this collection value.
00:51:50  
00:51:50  
00:51:50  Error: Invalid index
00:51:50  
00:51:50    on .terraform/modules/local_vpc/terraform-aws-vpc-2.21.0/main.tf line 989, in resource "aws_route_table_association" "public":
00:51:50   989:   route_table_id = aws_route_table.public[0].id
00:51:50      |----------------
00:51:50      | aws_route_table.public is empty tuple
00:51:50  
00:51:50  The given key does not identify an element in this collection value.
```
- Call to function "element" failed: cannot use element function with an empty list.

- The given key does not identify an element in this collection value.

>  Also trying single_nat_gateway & one_nat_gateway_per_az but still getting same error

**Comment by zelfick** [comment] 2020-08-08 01:03
You can fix as someone previously mention just delete the  files terraform.tfstate, terraform.tfstate.backup, and run again the plan.
The problem appears because something was deleted outside terraform and the terraform state got desynchronized

**Comment by antonbabenko** [comment] 2020-08-17 11:46
I think all of these problems are related, and very hard to fix for all combinations of parameters and flows (create/update).

If problem exists, please provide exact set of arguments you specify to the module, so that we (@terraform-aws-modules/triage-supporters and others) can try to reproduce the exact issue on our end.

Also, try to run configurations in [examples/simple-vpc](https://github.com/terraform-aws-modules/terraform-aws-vpc/tree/master/examples/simple-vpc) with updated arguments to reduce the scope of an issue in your environment.

**Comment by mkielar** [comment] 2020-09-28 07:38
We're facing this issue with 2.54.0 and have following errors reported for our DEV environment (which are by definition cut down to absolute minimum):

```
Error: Error in function call
  on .terraform/modules/core_infrastructure.main_vpc.vpc/vpc-endpoints.tf line 360, in resource "aws_vpc_endpoint" "ecr_api":
 360:   subnet_ids          = coalescelist(var.ecr_api_endpoint_subnet_ids, aws_subnet.private.*.id)
    |----------------
    | aws_subnet.private is empty tuple
    | var.ecr_api_endpoint_subnet_ids is empty list of string
Call to function "coalescelist" failed: no non-null arguments.
Error: Error in function call
  on .terraform/modules/core_infrastructure.main_vpc.vpc/vpc-endpoints.tf line 540, in resource "aws_vpc_endpoint" "monitoring":
 540:   subnet_ids          = coalescelist(var.monitoring_endpoint_subnet_ids, aws_subnet.private.*.id)
    |----------------
    | aws_subnet.private is empty tuple
    | var.monitoring_endpoint_subnet_ids is empty list of string
Call to function "coalescelist" failed: no non-null arguments.
```

The configuration we set for the module is:
```
vpc_cidr                   = "10.0.0.0/18"
vpc_az_count_private       = 2 # Need at least 2 for ALBs
vpc_az_count_database      = 2 # Need at least 2 for ALBs
vpc_az_count_public        = 2 # Need at least 2 for RDSs
vpc_enable_nat_gateway     = true
vpc_one_nat_gateway_per_az = false
vpc_single_nat_gateway     = true
```

The weird thing is the notification that `aws_subnet.private is empty tuple`, when we explicitely request 2 private subnets.
I also wonder if/how that issue was related to https://github.com/hashicorp/terraform/issues/21370.

Oh, and one more. Our terraform jobs work correctly on 2.48.0. It was the attempted migration to 2.54.0 that causes that issue.

We're using Terraform 0.12.29 AWS Provider 3.8.0.

**Comment by surajnarwade** [comment] 2021-01-19 21:53
I am facing similar issue where I provide:

```
public_subnets       = []
```

**Comment by antonbabenko** [comment] 2021-01-20 09:27
NAT gateway resides in the public subnet. Private subnets may have NAT gateway, which makes them also requiring public subnets to be set. `public_subnets` should not be empty for this reason.

Please provide a complete set of arguments as-is that you pass to this module. It is just impossible to help without seeing code.

**Comment by jungwookim** [comment] 2021-03-22 07:39
@antonbabenko Could you look into [this thread](https://github.com/terraform-aws-modules/terraform-aws-vpc/issues/400#issuecomment-594802782)? Some people get this problem too.

**Comment by antonbabenko** [comment] 2021-03-22 08:31
@jungwookim I wrote before that such issues are very hard to fix for all combinations of parameters and flows (create/update) and the only solution which comes to my mind now is to _hint_ terraform by doing smaller changes at once:
1. change one argument and apply it, then change another one and apply again
2. `terraform apply -target=module.vpc.aws_nat_gateway` (or similar)

> Please provide a complete set of arguments as-is that you pass to this module. It is just impossible to help without seeing code.

Debugging invisible configurations is very time-consuming.

I am going to close this issue.

**Closed by antonbabenko** 2021-03-22 08:31 UTC

**Comment by jungwookim** [comment] 2021-03-22 08:38
@antonbabenko Thanks for a quick review. That makes sense.

**Comment by mluds** [comment] 2021-03-26 22:41
In my case I needed to delete the terraform state file stored in S3
